### ISSUE TITLE
[coroutine] data race issue

### ISSUE THREAD

**Issue by jamboree** [ned14/afio#3]
I'm not familiar with AFIO, but by viewing the code, I suspect there's a data race between the IO thread and the thread running the coroutine.

In async_file_handle, the [completion handle](https://github.com/ned14/afio/blob/master/include/afio/v2.0/async_file_handle.hpp#L371) has some shared state (i.e. `_suspended` and `_result`). When the completion handle is called in the IO thread, the await_xxx() may be called  in the coroutine's thread simultaneously, hence the data race on the shared state.

Of course, if the coroutine always runs on the same IO thread, you'll be fine, but I don't think AFIO wants to impose such a limitation, does it?

**Comment by ned14** [comment]
Firstly, my apologies for the complete lack of documentation on `async_file_handle` and `io_service`. I just pushed some docs, they should be live shortly.

> Of course, if the coroutine always runs on the same IO thread, you'll be fine, but I don't think AFIO wants to impose such a limitation, does it?

And this is exactly the case: `io_service` is permanently attached to its creating thread, and all `async_file_handle`'s using that i/o service must also be solely used from the same thread. You can, of course, create many kernel threads, each with their own `io_service`, and distribute the work manually across them. But you probably don't want to do that. File i/o is not socket i/o.

**Comment by jamboree** [comment]
Thanks for the clarification. I didn't expect AFIO to be so different from ASIO.

However, it's not uncommon that one launches a coroutine in another thread, in which case the coroutine must schedule itself onto the `io_service` first.

I'd suggest you provide a convenient awaiter `co_schedule` to do  this:
```c++
co_await co_schedule(service); // calls io_service::post if not in the same thread
co_await co_write(...); // now it's safe to do async op on the service
```

**Comment by ned14** [comment]
> Thanks for the clarification. I didn't expect AFIO to be so different from ASIO.

Hardware and the OS behave quite differently now than they did when ASIO was designed a decade ago or so. If Chris were starting ASIO today, it'd have the same lightweight reactor model as AFIO. Dispatching to a thread pool comes with really awful > 99% latencies, it affects file i/o badly which is more much cache heavy than socket i/o. I've often said in my talks that with file i/o you really should just go synchronous almost all of the time, it annoyed me enough with Eric's blog post using range and coroutines with libuv I nearly emailed him to give out :). Synchronous = memcpy if it's cached. And the next gen DAX storage devices _are_ memory where doing anything but mapping them into memory is stupid. AFIO gained `mapped_file_handle` recently thanks to Intel loaning me access to a DAX device. Painful construction and extension costs, but otherwise boy does it fly. Storage is going to become very exciting next few years as those DAX devices reach the consumer level.

> I'd suggest you provide a convenient awaiter co_schedule to do this:

I've implemented this as `co_post_self_to_run()` which I felt more descriptive.

It ought to work, but as VS2017 still can't compile AFIO due to ICE, it's untested.

**Comment by jamboree** [comment]
>with file i/o you really should just go synchronous almost all of the time

I think the A in AFIO means asynchronous, no?

>VS2017 still can't compile AFIO due to ICE

I'm playing AFIO with VS2017, I have a few workaround for the ICE. In short, replace the `base(...)` with `base{...}` for outcome/result makes the compiler happy.

**Comment by ned14** [comment]
> I think the A in AFIO means asynchronous, no?

It does. But the empirical testing just doesn't support it being wise to actually _use_ async for much any more. It can still make sense for `O_DIRECT` i/o onto spinning rust storage. For everything else, synchronous i/o will be (much) faster.

The cause is that kernels have vastly improved their file i/o latencies (except for Windows) in recent years to the point where the overhead of setting up async and tearing it down is now relatively quite expensive. I actually sent my AFIO results from the Intel testing to Microsoft because I'd compared Windows 10, Linux and FreeBSD head to head. The Windows kernel engineers were genuinely appalled. Nobody had thought to look deeply at synchronous small block i/o, after all, they never see bug reports land on that kind of i/o. Yet all of us notice it any time we do a git checkout on Windows, and wonder how the hell it can be so slow.

>I'm playing AFIO with VS2017, I have a few workaround for the ICE. In short, replace the base(...) with base{...} for outcome/result makes the compiler happy.

I won't bore you with the expletives I have been uttering these last few minutes. Fuck Microsoft is the nicest thing I can say.

And to you, **thank you**.

**Comment by mdrost** [comment]
How is ASIO not lightweight? If ASIO is so heavy could AFIO be enhanced to replace ASIO?

**Comment by ned14** [comment]
> How is ASIO not lightweight?

Lots of things. It provides threading, task, coroutine and strand support. It templates its public APIs so it can consume arbitrary STL iterator inputs. It's also _huge_, look at how much source code is in there.

It also does a lot of malloc and mutex locking if you examine its core reactor. Unavoidable given its design, and can be ameliorated with custom allocators and custom mutex. But AFIO has no mutexs nor allocation at all (when scheduling an i/o, you can supply scratch memory for that i/o to use, if you don't AFIO calls malloc and free for you).

> If ASIO is so heavy could AFIO be enhanced to replace ASIO?

The ship sailed on ASIO's design a long time ago. Nothing can, or should, be done about it now. ASIO is a great library and perfectly fine for 99% of networking i/o users out there.

But could AFIO's reactor replace ASIO's? Not really. The need for i/o reactors is less now than ever. Kernels are so much faster than they were at synchronous i/o, and hardware is much better than it was. 80% of AFIO is synchronous, and I expect 95% of users will never use the async facilities at all because they'll be slower than the alternatives.

The future for storage is DAX where the entire storage device appears as RAM to the CPU. AFIO is designed for that world, not so much spinning rust.
