### ISSUE TITLE
prebuilt links for Linux and MacOS are broken

### ISSUE THREAD

**Issue by blastmaster** [ned14/afio#5]
Hi, I get a 404 HTTP code for the links to the prebuild x64 Linux and MacOS images.
The latest sources and windows binaries downloads seems to work.

**Comment by ned14** [comment]
Hmm, that's odd. I'll look into it. Thanks for the report.

**Comment by ned14** [comment]
Yeah, so I'd borked the scripts generating the prebuilt binaries. Sorry. It should cycle shortly.

Note that OS X hasn't compiled properly in a long time, as we need a Filesystem TS installed, so prebuilt binaries for OS X will take as long as it takes for Travis to install a Filesystem TS with XCode. But Linux and Windows should be fine.

**Comment by ned14** [comment]
Ok, looks like all the asan tests are failing on Linux. It won't be AFIO, it'll be Travis, but it'll be the weekend before I can fix it. Also, none of the prebuilt binaries are currently uploading. This is because I upgraded my server infrastructure from dedi4 to dedi5, and dedi5 is based on docker i.e. uploads go into a VM which is read only. So we're seeing 403 Forbidden. I'll figure out something better, but it'll take me a few days of pondering. I'll be back on this soon. Sorry for the delay.

**Comment by ned14** [comment]
Looks to be working again, at least for Windows and Linux. Apologies for the length of time taken.
