### ISSUE TITLE
Write-Scatter example not working.

### ISSUE THREAD

**Issue by harryherold** [ned14/afio#7]
I build the writer scatter example and got following error during the runtime:
```
use_cases: ../include/afio/v2.0/detail/impl/posix/io_handle.ipp:155: virtual afio_v2_d74b56b5::io_handle::io_result<gsl::span<afio_v2_d74b56b5::io_handle::const_buffer_type> > afio_v2_d74b56b5::io_handle::write(afio_v2_d74b56b5::io_handle::io_request<gsl::span<afio_v2_d74b56b5::io_handle::const_buffer_type> >, afio_v2_d74b56b5::deadline): Assertion `(reinterpret_cast<uintptr_t>(iov[n].iov_base) & 511) == 0' failed.
Aborted (core dumped)
```
Btw, are there some simple examples how to use the interface?

**Comment by harryherold** [comment]
When compiling with ```-DNDEBUG``` , the app is working fine.
It seems the check is wrong.

**Comment by ned14** [comment]
Ah, that's because they were never supposed to be actually executed :). They are just demos of how you would use it.

The check is correct. Input buffers when caching is `only_metadata` must be aligned to, and be a multiple of, the device's native block alignment. The check for 511 is only a quick sanity check.

I'll add a comment there to that test to point out it cannot work.

With regard to simple examples of how to use, you have already seen them. If you'd like an example of use different to those already there, please do suggest one. I am happy to extend the list of use examples.
